routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', '/admin/home');

Route::prefix("admin")->group(function(){
    Auth::routes();
});

Route::middleware('auth')
    ->prefix("admin")
    ->group(
        function () {
            Route::namespace('Dashboard')
            ->group(
                function () {
                    Route::get('home', 'DashboardController@index')->name('home');
                    Route::post('progress', 'DashboardController@progress')->name('dashboard.progress');
                    Route::post('chartFinding', 'DashboardController@chartFinding')->name('dashboard.chartFinding');
                    Route::post('chartFollowup', 'DashboardController@chartFollowup')->name('dashboard.chartFollowup');
                    Route::post('chartStage', 'DashboardController@chartStage')->name('dashboard.chartStage');
                    Route::get('language/{lang}/setLang', 'DashboardController@setLang')->name('setLang');
                }
            );

            // Ajax
            Route::prefix('ajax')
                ->name('ajax.')
                ->group(
                    function () {
                        Route::post('saveTempFiles', 'AjaxController@saveTempFiles')->name('saveTempFiles');
                        Route::delete('file/{id}', 'AjaxController@deletTempFile')->name('deleteTempFile');
                        Route::get('testNotification/{emails}', 'AjaxController@testNotification')->name('testNotification');
                        Route::post('userNotification', 'AjaxController@userNotification')->name('userNotification');
                        Route::get('userNotification/{notification}/read', 'AjaxController@userNotificationRead')->name('userNotificationRead');
                        // Ajax Modules
                        Route::post('{search}/selectRole', 'AjaxController@selectRole')->name('selectRole');
                        Route::post('{search}/selectUser', 'AjaxController@selectUser')->name('selectUser');
                        Route::post('{search}/selectTrainingType', 'AjaxController@selectTrainingType')->name('selectTrainingType');
                        Route::post('{search}/selectTraining', 'AjaxController@selectTraining')->name('selectTraining');
                    }
                );

            // Setting
            Route::namespace('Setting')
            ->prefix('setting')
            ->name('setting.')
            ->group(
                function () {
                    Route::namespace('Role')
                        ->group(
                            function () {
                                Route::get('role/import', 'RoleController@import')->name('role.import');
                                Route::post('role/importSave', 'RoleController@importSave')->name('role.importSave');
                                Route::get('role/{record}/permit', 'RoleController@permit')->name('role.permit');
                                Route::patch('role/{record}/grant', 'RoleController@grant')->name('role.grant');
                                Route::grid('role', 'RoleController');
                            }
                        );
                    Route::namespace('Permission')
                    ->group(
                        function () {
                            Route::get('permission/import', 'PermissionController@import')->name('permission.import');
                            Route::post('permission/importSave', 'PermissionController@importSave')->name('permission.importSave');
                            Route::grid('permission', 'PermissionController');
                        }
                    );
                    // Route::namespace('Flow')
                    //     ->group(
                    //         function () {
                    //             Route::get('flow/import', 'FlowController@import')->name('flow.import');
                    //             Route::post('flow/importSave', 'FlowController@importSave')->name('flow.importSave');
                    //             Route::grid('flow', 'FlowController');
                    //         }
                    //     );
                    Route::namespace('User')
                        ->group(
                            function () {
                                Route::get('user/import', 'UserController@import')->name('user.import');
                                Route::post('user/importSave', 'UserController@importSave')->name('user.importSave');
                                Route::post('user/{record}/resetPassword', 'UserController@resetPassword')->name('user.resetPassword');
                                Route::grid('user', 'UserController');

                                Route::get('profile', 'ProfileController@index')->name('profile.index');
                                Route::post('profile', 'ProfileController@updateProfile')->name('profile.updateProfile');
                                Route::get('profile/notification', 'ProfileController@notification')->name('profile.notification');
                                Route::post('profile/gridNotification', 'ProfileController@gridNotification')->name('profile.gridNotification');
                                Route::get('profile/activity', 'ProfileController@activity')->name('profile.activity');
                                Route::post('profile/gridActivity', 'ProfileController@gridActivity')->name('profile.gridActivity');
                                Route::get('profile/changePassword', 'ProfileController@changePassword')->name('profile.changePassword');
                                Route::post('profile/changePassword', 'ProfileController@updatePassword')->name('profile.updatePassword');
                            }
                        );
                    Route::namespace('Activity')
                        ->group(
                            function () {
                                Route::get('activity/export', 'ActivityController@export')->name('activity.export');
                                Route::grid('activity', 'ActivityController');
                            }
                        );
                }
            );

            // Master
            Route::namespace("Master")->prefix("master")->name("master.")->group(function() {
                Route::grid("training-types", "TrainingTypeController");
                Route::grid("trainings", "TrainingController");
                Route::grid("certificates", "CertificateController");
            });

            Route::namespace("Transaction")->prefix("transaction")->name("transaction.")->group(function() {
                Route::grid("participants", "Participant\ParticipantController");
                Route::grid("certificates", "Participant\ParticipantCertificateController");
            });

            // Web Transaction Modules
            foreach (\File::allFiles(__DIR__ . '/webs') as $file) {
                require $file->getPathname();
            }
        }
    );

app/Http/Controllers/API/BaseController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BaseController extends Controller
{
    /**
     * success response method.
     *
     * @return \Illuminate\Http\Response
     */
    public function sendResponseSuccess($data, $message = '')
    {
        $additionalData = [
            'success' => true,
            'message' => $message,
        ];

        if (is_array($data) === true) {
            // pure array not collection

            if(array_key_exists("data", $data)) {
                $response = array_merge($additionalData, $data);
            } else {
                $response = array_merge($additionalData, ['data' => $data]);
            }
        }else{
            // Collection
            $response = $data->additional($additionalData);
        }

        return $response;
    }

    /**
     * return error response.
     *
     * @return \Illuminate\Http\Response
     */
    public function sendResponseError($data = [], $errorMessages='', $code = 400)
    {
        $response = [
            'success' => false,
            'message' => $errorMessages,
        ];
        if (! empty($data)) {
            $response['data'] = $data;
        }

        return response()->json($response, $code);
    }

    public function sendResponseValidationError(array $data, string $meessage = "Validation errors", int $code = 422) {
        $response = [
            'success' => false,
            'message' => $meessage,
        ];

        $tempData = [];

        if(!empty($data)) {
            foreach($data as $key => $row) {
                $temp = [
                    "field" => $key,
                    "message" => $row[0]
                ];
                array_push($tempData, $temp);
            }
        }
        $response["data"] = $tempData;
        return response()->json($response, $code);
    }
}

resources/views/layouts/base/aside.blade.php
<div id="kt_aside" class="aside aside-left aside-fixed d-flex flex-column flex-row-auto page-with-light-sidebar">
    {{-- Brand --}}
    <div class="brand flex-column-auto pr-3" id="kt_brand">
        <div class="brand-logo m-auto">
            <a href="{{ url('/') }}">
                <img src="{{ asset(config('base.logo.aside')) }}" alt="Image" style="max-width: 170px; max-height: 40px;"/>
            </a>
        </div>

        <button class="brand-toggle btn btn-sm px-0" id="kt_aside_toggle">
            {!! \Base::getSVG("assets/media/svg/icons/Navigation/Angle-double-left.svg", "svg-icon-xl") !!}
        </button>
    </div>

    {{-- Aside menu --}}
    <div class="aside-menu-wrapper flex-column-fluid" id="kt_aside_menu_wrapper">
        <div
            id="kt_aside_menu"
            class="aside-menu my-4"
            resize="true"
            data-menu-vertical="1"
            data-menu-scroll="1"
            data-menu-dropdown-timeout="250">

            @if (config('base.custom-menu'))
                {{-- Custom menu --}}
                <div class="custom-menu">
                    <ul class="menu-nav nav">
                       @foreach (config('backendmenu') as $menu)
                           @if (!empty($menu['perms']) && !auth()->user()->checkPerms($menu['perms'].'.view'))
                               @continue;
                           @endif
                           {!! \Base::renderMenuTree($menu) !!}
                       @endforeach
                    </ul>
                </div>
            @else
                {{-- Default metronic menu --}}
                <ul class="menu-nav">
                    @foreach (config('backendmenu') as $menu)
                        @if (isset($menu['permission']) && !auth()->user()->checkPerms($menu['permission']))
                            @continue;
                        @endif
                        {!! \Base::renderAsideMenu($menu) !!}
                    @endforeach
                </ul>
            @endif
        </div>
    </div>
</div>

resources/views/layouts/base/footer.blade.php
<div class="footer bg-white py-4 d-flex flex-lg-column" id="kt_footer">
    <div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
        <div class="text-dark order-2 order-md-1">
            <span class="text-muted font-weight-bold mr-2">{{ date('Y') }}©</span>
            <a href="{{ url('/') }}" target="_blank" class="text-dark-75 text-hover-primary">
                {{ config('base.company') }}
            </a>
        </div>
    </div>
</div>

resources/views/layouts/base/header.blade.php
<div id="kt_header" class="header header-fixed">
    <div class="container-fluid d-flex align-items-stretch justify-content-between">
        {{-- @include('layouts.base.header-menu') --}}
        <div></div>

        <div class="topbar">
            <div class="dropdown dropdown-notification">
                @php
                    $count = auth()->user()->notifications()->latest()->wherePivot('readed_at', NULL)->count();
                @endphp
                <div class="topbar-item" data-toggle="dropdown" data-offset="10px,0px">
                    <div class="btn btn-icon btn-clean btn-dropdown btn-lg mr-1 pulse pulse-success">
                        <i class="far fa-bell"></i>
                        <span class="pulse-ring"></span>
                    </div>
                    <div class="user-notification-badge {{ $count === 0 ? 'hide' : '' }}" 
                        style="margin-top: -20px; margin-left: -20px; z-index: 11">
                        <span class="label label-light-danger label-pill label-inline mr-2">{{ $count }}</span>
                    </div>
                </div>
                <div class="dropdown-menu p-0 m-0 dropdown-menu-right dropdown-menu-anim-up dropdown-menu-lg">
                    <div class="d-flex flex-column flex-center py-10 bgi-size-cover bgi-no-repeat rounded-top bg-app opacity-80">
                        <h4 class="d-flex flex-center rounded-top">
                            <span class="text-white">User Notifications</span>
                            <span class="user-notification-header btn btn-text btn-success btn-sm font-weight-bold btn-font-md ml-2 {{ $count === 0 ? 'hide' : '' }}">
                                <span>{{ $count }} new</span>
                            </span>
                        </h4>
                    </div>
                    <div class="row row-paddingless">
                        <div class="col-12">
                            <div class="base-notification-wrapper" 
                                data-url="{{ route('ajax.userNotification') }}"
                                data-last-user-notification="{{ auth()->user()->getLastNotificationId() }}">
                                @include('layouts.base.notification')
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="dropdown d-none">
                <div class="topbar-item" data-toggle="dropdown" data-offset="10px,0px" aria-expanded="false">
                    <div class="btn btn-icon btn-clean btn-dropdown btn-lg mr-1">
                        @php
                            $flagEn = '226-united-states.svg';
                            $flagId = '004-indonesia.svg';
                            $icon = \App::getLocale() == 'en' ? $flagEn : $flagId;
                        @endphp 
                        <img class="h-20px w-20px rounded-sm" src="{{ asset('assets/media/svg/flags/'.$icon) }}" alt="Image">
                    </div>
                </div>
                <div class="dropdown-menu p-0 m-0 dropdown-menu-anim-up dropdown-menu-sm dropdown-menu-right">
                    <ul class="navi navi-hover py-4">
                        <li class="navi-item active">
                            <a href="{{ route('setLang', 'id') }}" class="navi-link">
                                <span class="symbol symbol-20 mr-3">
                                    <img src="{{ asset('assets/media/svg/flags/'.$flagId) }}" alt="Image">
                                </span>
                                <span class="navi-text">Indonesia</span>
                            </a>
                        </li>
                        <li class="navi-item">
                            <a href="{{ route('setLang', 'en') }}" class="navi-link">
                                <span class="symbol symbol-20 mr-3">
                                    <img src="{{ asset('assets/media/svg/flags/'.$flagEn) }}" alt="Image">
                                </span>
                                <span class="navi-text">English</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="dropdown">
                <div class="topbar-item" data-toggle="dropdown" data-offset="0px,0px" aria-expanded="false">
                    <div class="btn btn-icon btn-clean d-flex align-items-center btn-lg px-md-2 w-md-auto">
                        <span class="link-text font-weight-bolder font-size-base d-none d-md-inline mr-4">{{ auth()->user()->name }}</span>
                        @if (auth()->user()->image)
                            <div class="symbol ssymbol-lg-35 symbol-25 symbol-light-success symbol-circle shadow">
                                <img src="{{ asset(auth()->user()->image_path) }}" alt="Image">
                                <i class="symbol-badge symbol-badge-bottom bg-success"></i>
                            </div>
                        @else
                            <span class="symbol symbol-lg-35 symbol-25 symbol-light-success">
                                <span class="symbol-label font-size-h5 font-weight-bold">
                                    {{ auth()->user()->name[0] }}
                                </span>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="dropdown-menu p-0 m-0 dropdown-menu-right dropdown-menu-anim-up dropdown-menu-lg p-0">
                    <div class="d-flex align-items-center p-8 rounded-top">
                        <div class="symbol symbol-md bg-light-primary mr-3 flex-shrink-0 shadow-sm">
                            <img src="{{ asset(auth()->user()->image_path) }}" alt="Image">
                        </div>

                        <div class="text-dark m-0 flex-grow-1 mr-3 font-size-h5">
                            <div class="font-weight-bold">{{ auth()->user()->name }}</div>
                            <div class="text-muted font-size-12">{{ auth()->user()->roles_imploded }}</div>
                        </div>
                    </div>
                    <div class="separator separator-solid"></div>
                    <div class="navi navi-spacer-x-0 pt-5">
                        <a href="{{ route('setting.profile.index') }}" class="navi-item px-8 base-content--replace">
                            <div class="navi-link">
                                <div class="navi-icon mr-2">
                                    <i class="flaticon2-calendar-3 text-success"></i>
                                </div>
                                <div class="navi-text">
                                    <div class="font-weight-bold">My Profile</div>
                                    <div class="text-muted">Account settings and more</div>
                                </div>
                            </div>
                        </a>
                        <a href="{{ route('setting.profile.notification') }}" class="navi-item px-8 base-content--replace">
                            <div class="navi-link">
                                <div class="navi-icon mr-2">
                                    <i class="flaticon2-rocket-1 text-danger"></i>
                                </div>
                                <div class="navi-text">
                                    <div class="font-weight-bold">My Notification</div>
                                    <div class="text-muted">All your notifications</div>
                                </div>
                            </div>
                        </a>
                        <a href="{{ route('setting.profile.activity') }}" class="navi-item px-8 base-content--replace">
                            <div class="navi-link">
                                <div class="navi-icon mr-2">
                                    <i class="flaticon2-rocket-1 text-danger"></i>
                                </div>
                                <div class="navi-text">
                                    <div class="font-weight-bold">My Activities</div>
                                    <div class="text-muted">All your activities</div>
                                </div>
                            </div>
                        </a>

                        <div class="navi-separator mt-3"></div>
                        <div class="navi-footer px-8 py-5 float-right">
                            <form action="<?= route('logout') ?>" method="POST">
                                @csrf
                                @method('POST')
                                <button type="submit" class="btn btn-light-primary font-weight-bold">Sign Out</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

resources/views/layouts/base/notification.blade.php
@if (isset($notifications) && count($notifications))
    <div class="navi navi-hover scroll my-4 user-notification-items"
        data-count="{{ auth()->user()->notifications()->wherePivot('readed_at', null)->count() }}"
        data-scroll="true" 
        style="min-height: 100px; max-height: 300px;">
        @foreach ($notifications as $item)
            <a href="{{ route('ajax.userNotificationRead', $item->id) }}" class="navi-item base-content--replace {{ $loop->last ? 'mb-7' : '' }}" >
                <div class="navi-link">
                    <div class="navi-icon mr-2 v-align-top">
                        <i class="flaticon2-notification {{ $item->pivot->readed_at ? '' : 'text-success' }}"></i>
                    </div>
                    <div class="navi-text">
                        <div class="text-bold text-app">{!! \Base::getModules($item->module) !!}</div>
                        <div class="text-normal">{!! $item->message !!}</div>
                        <div class="text-muted">Created By: {{ $item->from_name }}</div>
                        <div class="text-muted">Created At: {{ $item->creationDate(false) }}</div>
                    </div>
                </div>
            </a>
        @endforeach
    </div>
    <div class="text-center">
        <div class="separator separator-solid  my-5"></div>
        <a href="{{ route('setting.profile.notification') }}" 
            class="btn btn-light-primary mb-3 base-content--replace">
            {{ 'Baca Semua' }} <i class="fas fa-angle-right ml-2"></i>
        </a>
    </div>
@else
    <div class="d-flex flex-center text-center text-muted min-h-200px">
        {{ __('Data tidak tersedia!') }}
    </div>
@endif

resources/views/layouts/base/subheader.blade.php
<div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-2">
            <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">
                @section('content-title')
                    {{ $title }}
                @show
            </h5>
            @section('content-breadcrumb')
                @if (count($breadcrumb) > 1)
                    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-5 bg-gray-200"></div>
                    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2">
                        <li class="breadcrumb-item text-muted">
                            <a href="{{ url('/') }}" class="text-muted base-content--replace">
                                <i class="fa fa-home"></i>
                            </a>
                        </li>
                        @foreach ($breadcrumb as $show => $link)
                            @if (!in_array(strtolower($show), ['home', 'dashboard']))
                                <li class="breadcrumb-item text-muted">
                                    <a href="{{ $link }}" class="text-muted base-content--replace">
                                        {{ __($show) }}
                                    </a>
                                </li>
                            @endif
                        @endforeach
                    </ul>
                @endif
            @show
        </div>

        <div class="d-flex align-items-center">
            @yield('buttons-right')
        </div>
    </div>
</div>