routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', '/admin/home');

Route::prefix("admin")->group(function(){
    Auth::routes();
});

Route::middleware('auth')
    ->prefix("admin")
    ->group(
        function () {
            Route::namespace('Dashboard')
            ->group(
                function () {
                    Route::get('home', 'DashboardController@index')->name('home');
                    Route::post('progress', 'DashboardController@progress')->name('dashboard.progress');
                    Route::post('chartFinding', 'DashboardController@chartFinding')->name('dashboard.chartFinding');
                    Route::post('chartFollowup', 'DashboardController@chartFollowup')->name('dashboard.chartFollowup');
                    Route::post('chartStage', 'DashboardController@chartStage')->name('dashboard.chartStage');
                    Route::get('language/{lang}/setLang', 'DashboardController@setLang')->name('setLang');
                }
            );

            // Ajax
            Route::prefix('ajax')
                ->name('ajax.')
                ->group(
                    function () {
                        Route::post('saveTempFiles', 'AjaxController@saveTempFiles')->name('saveTempFiles');
                        Route::delete('file/{id}', 'AjaxController@deletTempFile')->name('deleteTempFile');
                        Route::get('testNotification/{emails}', 'AjaxController@testNotification')->name('testNotification');
                        Route::post('userNotification', 'AjaxController@userNotification')->name('userNotification');
                        Route::get('userNotification/{notification}/read', 'AjaxController@userNotificationRead')->name('userNotificationRead');
                        // Ajax Modules
                        Route::post('{search}/selectRole', 'AjaxController@selectRole')->name('selectRole');
                        Route::post('{search}/selectUser', 'AjaxController@selectUser')->name('selectUser');
                        Route::post('{search}/selectTrainingType', 'AjaxController@selectTrainingType')->name('selectTrainingType');
                        Route::post('{search}/selectTraining', 'AjaxController@selectTraining')->name('selectTraining');
                    }
                );

            // Setting
            Route::namespace('Setting')
            ->prefix('setting')
            ->name('setting.')
            ->group(
                function () {
                    Route::namespace('Role')
                        ->group(
                            function () {
                                Route::get('role/import', 'RoleController@import')->name('role.import');
                                Route::post('role/importSave', 'RoleController@importSave')->name('role.importSave');
                                Route::get('role/{record}/permit', 'RoleController@permit')->name('role.permit');
                                Route::patch('role/{record}/grant', 'RoleController@grant')->name('role.grant');
                                Route::grid('role', 'RoleController');
                            }
                        );
                    Route::namespace('Permission')
                    ->group(
                        function () {
                            Route::get('permission/import', 'PermissionController@import')->name('permission.import');
                            Route::post('permission/importSave', 'PermissionController@importSave')->name('permission.importSave');
                            Route::grid('permission', 'PermissionController');
                        }
                    );
                    // Route::namespace('Flow')
                    //     ->group(
                    //         function () {
                    //             Route::get('flow/import', 'FlowController@import')->name('flow.import');
                    //             Route::post('flow/importSave', 'FlowController@importSave')->name('flow.importSave');
                    //             Route::grid('flow', 'FlowController');
                    //         }
                    //     );
                    Route::namespace('User')
                        ->group(
                            function () {
                                Route::get('user/import', 'UserController@import')->name('user.import');
                                Route::post('user/importSave', 'UserController@importSave')->name('user.importSave');
                                Route::post('user/{record}/resetPassword', 'UserController@resetPassword')->name('user.resetPassword');
                                Route::grid('user', 'UserController');

                                Route::get('profile', 'ProfileController@index')->name('profile.index');
                                Route::post('profile', 'ProfileController@updateProfile')->name('profile.updateProfile');
                                Route::get('profile/notification', 'ProfileController@notification')->name('profile.notification');
                                Route::post('profile/gridNotification', 'ProfileController@gridNotification')->name('profile.gridNotification');
                                Route::get('profile/activity', 'ProfileController@activity')->name('profile.activity');
                                Route::post('profile/gridActivity', 'ProfileController@gridActivity')->name('profile.gridActivity');
                                Route::get('profile/changePassword', 'ProfileController@changePassword')->name('profile.changePassword');
                                Route::post('profile/changePassword', 'ProfileController@updatePassword')->name('profile.updatePassword');
                            }
                        );
                    Route::namespace('Activity')
                        ->group(
                            function () {
                                Route::get('activity/export', 'ActivityController@export')->name('activity.export');
                                Route::grid('activity', 'ActivityController');
                            }
                        );
                }
            );

            // Master
            Route::namespace("Master")->prefix("master")->name("master.")->group(function() {
                Route::grid("training-types", "TrainingTypeController");
                Route::grid("trainings", "TrainingController");
                Route::grid("certificates", "CertificateController");
            });

            Route::namespace("Transaction")->prefix("transaction")->name("transaction.")->group(function() {
                Route::grid("participants", "Participant\ParticipantController");
                Route::grid("certificates", "Participant\ParticipantCertificateController");
            });

            // Web Transaction Modules
            foreach (\File::allFiles(__DIR__ . '/webs') as $file) {
                require $file->getPathname();
            }
        }
    );

app/Http/Controllers/Setting/Activity/ActivityController.php
<?php

namespace App\Http\Controllers\Setting\Activity;

use App\Exports\Setting\ActivityExport;
use App\Http\Controllers\Controller;
use App\Models\Globals\Activity;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class ActivityController extends Controller
{
    protected $module = 'setting_activity';
    protected $routes = 'setting.activity';
    protected $views = 'setting.activity';
    protected $perms = 'setting_activity';

    public function __construct()
    {
        $this->prepare([
            'module' => $this->module,
            'routes' => $this->routes,
            'views' => $this->views,
            'permission' => $this->perms.'.view',
            'title' => 'P4EKRAF',
            'breadcrumb' => [
                'Pengaturan Umum' => route($this->routes.'.index'),
                'P4EKRAF' => route($this->routes.'.index'),
            ]
        ]);
    }

    public function index()
    {
        $this->prepare([
            'tableStruct' => [
                'datatable_1' => [
                    $this->makeColumn('name:num'),
                    $this->makeColumn('name:module|label:Modul|className:text-left'),
                    $this->makeColumn('name:message|label:Deskripsi|className:text-left'),
                    $this->makeColumn('name:created_by'),
                    // $this->makeColumn('name:action'),
                ],
            ],
        ]);
        return $this->render($this->views.'.index');
    }

    public function grid()
    {
        $records = Activity::grid()->filters()->dtGet();

        return \DataTables::of($records)
            ->addColumn('num', function ($record) {
                return request()->start;
            })
            ->addColumn('module', function ($record) {
                return $record->show_module;
            })
            ->addColumn('message', function ($record) {
                return $record->show_message;
            })
            ->editColumn('created_by', function ($record) {
                return $record->createdByRaw();
            })
            ->rawColumns(['action','created_by'])
            ->make(true);
    }



    public function export()
    {
        return Excel::download(new ActivityExport, date('Y-m-d').' P4EKRAF.xlsx');
    }
}

app/Http/Controllers/Setting/Flow/FlowController.php
<?php

namespace App\Http\Controllers\Setting\Flow;

use App\Exports\GenerateExport;
use App\Http\Controllers\Controller;
use App\Http\Requests\Setting\Flow\FlowRequest;
use App\Models\Globals\Menu;
use Illuminate\Http\Request;

class FlowController extends Controller
{
    protected $module = 'setting_flow';
    protected $routes = 'setting.flow';
    protected $views = 'setting.flow';
    protected $perms = 'setting';

    public function __construct()
    {
        $this->prepare(
            [
                'module' => $this->module,
                'routes' => $this->routes,
                'views' => $this->views,
                'perms' => $this->perms,
                'permission' => $this->perms . '.view',
                'title' => 'Flow Approval',
                'breadcrumb' => [
                    'Pengaturan Umum' => route($this->routes . '.index'),
                    'Flow Approval' => route($this->routes . '.index'),
                ]
            ]
        );
    }

    public function index()
    {
        $this->prepare(
            [
                'tableStruct' => [
                    'datatable_1' => [
                        $this->makeColumn('name:num'),
                        $this->makeColumn('name:menu|label:Menu|className:text-left|sortable:false'),
                        $this->makeColumn('name:flows|label:Flow Approval|className:text-center|sortable:false'),
                        $this->makeColumn('name:updated_by|label:Diperbarui Oleh|width:180px|sortable:false'),
                        $this->makeColumn('name:action'),
                    ],
                ],
            ]
        );
        return $this->render(
            $this->views . '.index'
        );
    }

    public function grid()
    {
        $records = Menu::grid()->filters()->dtGet();
        // return $records;

        return \DataTables::of($records)
            ->addColumn(
                'num',
                function ($record) {
                    return request()->start;
                }
            )
            ->addColumn(
                'menu',
                function ($record) {
                    return ($record->parent ? '<span class="pl-4">&#8627;</span> ' : '') . $record->show_module;
                }
            )
            ->addColumn(
                'flows',
                function ($record) {
                    if ($record->flows->count() == 0) {
                        return "";
                    }

                    $html = '<div class="d-flex align-items-center justify-content-center">';
                    $colors = [
                        1 => 'primary',
                        2 => 'info',
                    ];
                    $orders = $record->flows()->get()->groupBy('order');
                    foreach ($orders as $i => $flows) {
                        foreach ($flows as $j => $flow) {
                            $html .= '<span class="label label-light-' . $colors[$flow->type] . ' font-weight-bold label-inline text-nowrap" data-toggle="tooltip" title="' . $flow->show_type . '">' . $flow->role->name . '</span>';

                            if (!($i === $orders->keys()->last() && $j === $flows->keys()->last())) {
                                $html .= '<i class="mx-2 fas fa-angle-double-right text-muted"></i>';
                            }
                        }
                    }
                    $html .= "</div>";

                    return $html;
                }
            )
            ->editColumn(
                'updated_by',
                function ($record) {
                    return $record->createdByRaw();
                }
            )
            ->addColumn(
                'action',
                function ($record) {
                    $actions = [];
                    if (!$record->child()->exists()) {
                        $actions[] = [
                            'type' => 'edit',
                            'page' => true,
                            'icon' => 'far fa-check-circle text-success',
                            'label' => 'Assign Approval',
                            'id' => $record->id,
                        ];
                    }
                    return $this->makeButtonDropdown($actions);
                }
            )
            ->rawColumns(['action', 'updated_by', 'menu', 'flows'])
            ->make(true);
    }

    public function edit(Menu $record)
    {
        return $this->render($this->views . '.edit', compact('record'));
    }

    public function update(FlowRequest $request, Menu $record)
    {
        return $record->handleStoreOrUpdate($request);
    }

    public function import()
    {
        if (request()->get('download') == 'template') {
            return $this->template();
        }
        return $this->render($this->views . '.import');
    }

    public function template()
    {
        $fileName = date('Y-m-d') . ' Template Import Data ' . $this->prepared('title') . '.xlsx';
        $records = Menu::grid()->whereNotNull('parent_id')->get();
        $colors = ['#3699FF', '#1BC5BD', '#8950FC', '#28C76F', '#FFA800'];

        $view = $this->views . '.template';
        $data['records'] = $records;
        $data['colors'] = $colors;

        return \Excel::download(new GenerateExport($view, $data), $fileName);
    }

    public function importSave(Request $request)
    {
        $request->validate(
            [
                'uploads.uploaded' => 'required',
                'uploads.temp_files_ids.*' => 'required',
            ],
            [],
            [
                'uploads.uploaded' => 'File',
                'uploads.temp_files_ids.*' => 'File',
            ]
        );

        $record = new Menu;
        return $record->handleImport($request);
    }
}

resources/views/setting/profile/activity.blade.php
@extends('layouts.page')

@section('content-title', $title)

@section('page')
    <div class="d-flex flex-row">
        @include($views.'.includes.profile-aside', ['tab' => 'activity'])

        <div class="flex-row-fluid ml-lg-8">
            <div class="card card-custom gutter-b">

                <div class="card-header py-3">
                    <div class="card-title align-items-start flex-column">
                        <h3 class="card-label font-weight-bolder text-dark">{{ __($title) }}</h3>
                        <span class="text-muted font-weight-bold font-size-sm mt-1">{{ __('Riwayat Aktivitas') }}</span>
                    </div>
                </div>

                <div class="card-body padding-20">
                	<table id="dataFilters" class="width-full">
                		<tbody>
                			<tr>
                				<td class="pb-2 valign-top td-filter-reset width-80px">
                					<div class="reset-filter mr-1 hide">
                						<button class="btn btn-secondary btn-icon width-full reset button" data-toggle="tooltip" data-original-title="Reset Filter"><i class="fas fa-sync"></i></button>
                					</div>
                					<div class="label-filter mr-1">
                						<button class="btn btn-secondary btn-icon width-full filter button" data-toggle="tooltip" data-original-title="Filter"><i class="fas fa-filter"></i></button>
                					</div>
                				</td>
                				<td>
                					<div class="row">
                						<div class="col-12 col-sm-6 col-xl-3 pb-2">
                							<select class="form-control base-plugin--select2-ajax filter-control"
                								data-post="module_name" 
                								data-placeholder="{{ __('Semua Modul') }}">
                								<option value="" selected>{{ __('Semua Modul') }}</option>
                								@foreach (\Base::getModules() as $key => $name)
                									<option value="{{ $key }}">{{ $name }}</option>
                								@endforeach
                							</select>
                						</div>
                						<div class="col-12 col-sm-6 col-xl-3 pb-2">
                							<input type="text" class="form-control filter-control" data-post="message" placeholder="{{ __('Deskripsi') }}">
                						</div>
                					</div>
                				</td>
                				<td class="text-right td-btn-create"></td>
                			</tr>
                		</tbody>
                	</table>
                	<div class="table-responsive">
                	    @if(isset($tableStruct['datatable_1']))
                		    <table id="datatable_1" class="table table-bordered is-datatable" style="width: 100%;" data-url="{{ $tableStruct['url'] }}">
                		        <thead>
                		            <tr>
                		                @foreach ($tableStruct['datatable_1'] as $struct)
                		                	<th class="text-center v-middle"
                		                		data-columns-name="{{ $struct['name'] ?? '' }}"
                		                		data-columns-data="{{ $struct['data'] ?? '' }}"
                		                		data-columns-label="{{ $struct['label'] ?? '' }}"
                		                		data-columns-sortable="{{ $struct['sortable'] === true ? 'true' : 'false' }}"
                		                		data-columns-width="{{ $struct['width'] ?? '' }}"
                		                		data-columns-class-name="{{ $struct['className'] ?? '' }}"
                		                		style="{{ isset($struct['width']) ? 'width: '.$struct['width'].'; ' : '' }}">
                		                		{{ $struct['label'] }}
                		                	</th>
                		                @endforeach
                		            </tr>
                		        </thead>
                		        <tbody></tbody>
                		    </table>
                	    @endif
                	</div>
                </div>

            </div>
        </div>
        
    </div>
@endsection

resources/views/setting/profile/changePassword.blade.php
@extends('layouts.page')

@section('page')
    <div class="d-flex flex-row">
        @include($views.'.includes.profile-aside', ['tab' => 'changePassword'])

        <div class="flex-row-fluid ml-lg-8">
            <div class="card card-custom gutter-b">

                <div class="card-header py-3">
                    <div class="card-title align-items-start flex-column">
                        <h3 class="card-label font-weight-bolder text-dark">{{ __($title) }}</h3>
                        <span class="text-muted font-weight-bold font-size-sm mt-1">{{ __('Informasi Pribadi') }}</span>
                    </div>
                </div>

                <form action="{{ route($routes.'.updatePassword') }}" method="post" autocomplete="off">
                    @csrf
                    @method('POST')

                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label text-right">{{ __('Password Lama') }}</label>
                            <div class="col-lg-9 col-xl-6 parent-group">
                                <div class="input-group input-group-lg input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="la la-key"></i>
                                        </span>
                                    </div>
                                    <input type="password" class="form-control" name="old_password" placeholder="{{ __('Password Lama') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label text-right">{{ __('Password Baru') }}</label>
                            <div class="col-lg-9 col-xl-6 parent-group">
                                <div class="input-group input-group-lg input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="la la-key"></i>
                                        </span>
                                    </div>
                                    <input type="password" class="form-control" name="new_password" placeholder="{{ __('Password Baru') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label text-right">{{ __('Konfirmasi Password Baru') }}</label>
                            <div class="col-lg-9 col-xl-6 parent-group">
                                <div class="input-group input-group-lg input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="la la-key"></i>
                                        </span>
                                    </div>
                                    <input type="password" class="form-control" name="new_password_confirmation" placeholder="{{ __('Konfirmasi Password Baru') }}">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer text-right">
                        @include('layouts.forms.btnSubmitPage')
                    </div>
                </form>

            </div>
        </div>
        
    </div>
@endsection

resources/views/setting/profile/create.blade.php
@extends('layouts.modal')

@section('action', route($routes.'.store'))

@section('modal-body')
	@method('POST')
	<div class="form-group row">
		<label class="col-md-4 col-form-label">{{ __('Nama') }}</label>
		<div class="col-md-8 parent-group">
			<input type="text" name="name" class="form-control" placeholder="{{ __('Nama') }}">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('NIK') }}</label>
		<div class="col-sm-8 parent-group">
			<input type="text" name="nik" class="form-control" placeholder="{{ __('NIK') }}">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Email') }}</label>
		<div class="col-sm-8 parent-group">
			<input type="email" name="email" class="form-control" placeholder="{{ __('Email') }}">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Password') }}</label>
		<div class="col-sm-8 parent-group">
			<input type="password" name="password" class="form-control" placeholder="{{ __('Password') }}">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Konfirmasi Password') }}</label>
		<div class="col-sm-8 parent-group">
			<input type="password" name="password_confirmation" class="form-control" placeholder="{{ __('Konfirmasi Password') }}">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Position') }}</label>
		<div class="col-sm-8 parent-group">
			<select name="position_id" class="form-control base-plugin--select2-ajax" 
				data-url="{{ route('ajax.selectPosition', 'all') }}"
				placeholder="{{ __('Position') }}">
				<option value="">{{ __('Pilih Salah Satu') }}</option>
			</select>
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Role') }}</label>
		<div class="col-sm-8 parent-group">
			<select name="roles[]" class="form-control base-plugin--select2-ajax" 
				data-url="{{ route('ajax.selectRole', 'all') }}"
				placeholder="{{ __('Role') }}">
				<option value="">{{ __('Pilih Salah Satu') }}</option>
			</select>
		</div>
	</div>
@endsection

resources/views/setting/profile/edit.blade.php
@extends('layouts.modal')

@section('action', route($routes.'.update', $record->id))

@section('modal-body')
	@method('PATCH')
	<div class="form-group row">
		<label class="col-md-4 col-form-label">{{ __('Nama') }}</label>
		<div class="col-md-8 parent-group">
			<input type="text" name="name" value="{{ $record->name }}" class="form-control" placeholder="{{ __('Nama') }}">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('NIK') }}</label>
		<div class="col-sm-8 parent-group">
			<input type="text" name="nik" value="{{ $record->nik }}" class="form-control" placeholder="{{ __('NIK') }}">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Email') }}</label>
		<div class="col-sm-8 parent-group">
			<input type="email" name="email" value="{{ $record->email }}" class="form-control" placeholder="{{ __('Email') }}">
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Position') }}</label>
		<div class="col-sm-8 parent-group">
			<select name="position_id" class="form-control base-plugin--select2-ajax" 
				data-url="{{ route('ajax.selectPosition', 'all') }}"
				data-placeholder="{{ __('Position') }}">
				@if ($record->position)
					<option value="{{ $record->position->id }}" selected>{{ $record->position->name }}</option>
				@endif
			</select>
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-4 col-form-label">{{ __('Role') }}</label>
		<div class="col-sm-8 parent-group">
			<select name="roles[]" class="form-control base-plugin--select2-ajax" 
				data-url="{{ route('ajax.selectRole', 'all') }}"
				data-placeholder="{{ __('Role') }}">
				<option value="">{{ __('Pilih Salah Satu') }}</option>
				@foreach ($record->roles as $val)
					<option value="{{ $val->id }}" selected>{{ $val->name }}</option>
				@endforeach
			</select>
		</div>
	</div>
@endsection

resources/views/setting/profile/notification.blade.php
@extends('layouts.page')

@section('page')
    <div class="d-flex flex-row">
        @include($views.'.includes.profile-aside', ['tab' => 'notification'])

        <div class="flex-row-fluid ml-lg-8">
            <div class="card card-custom gutter-b">

                <div class="card-header py-3">
                    <div class="card-title align-items-start flex-column">
                        <h3 class="card-label font-weight-bolder text-dark">{{ __($title) }}</h3>
                        <span class="text-muted font-weight-bold font-size-sm mt-1">{{ __('Riwayat Notifikasi') }}</span>
                    </div>
                </div>

                <div class="card-body padding-20">
                	<table id="dataFilters" class="width-full">
                		<tbody>
                			<tr>
                				<td class="pb-2 valign-top td-filter-reset width-80px">
                					<div class="reset-filter mr-1 hide">
                						<button class="btn btn-secondary btn-icon width-full reset button" data-toggle="tooltip" data-original-title="Reset Filter"><i class="fas fa-sync"></i></button>
                					</div>
                					<div class="label-filter mr-1">
                						<button class="btn btn-secondary btn-icon width-full filter button" data-toggle="tooltip" data-original-title="Filter"><i class="fas fa-filter"></i></button>
                					</div>
                				</td>
                				<td>
                					<div class="row">
                						<div class="col-12 col-sm-6 col-xl-3 pb-2">
                							<select class="form-control base-plugin--select2-ajax filter-control"
                								data-post="module_name" 
                								data-placeholder="{{ __('Semua Modul') }}">
                								<option value="" selected>{{ __('Semua Modul') }}</option>
                								@foreach (\Base::getModules() as $key => $name)
                                                    <option value="{{ $key }}">{{ $name }}</option>
                                                @endforeach
                							</select>
                						</div>
                						<div class="col-12 col-sm-6 col-xl-3 pb-2">
                							<input type="text" class="form-control filter-control" data-post="message" placeholder="{{ __('Deskripsi') }}">
                						</div>
                					</div>
                				</td>
                				<td class="text-right td-btn-create"></td>
                			</tr>
                		</tbody>
                	</table>
                	<div class="table-responsive">
                	    @if(isset($tableStruct['datatable_1']))
                		    <table id="datatable_1" class="table table-bordered is-datatable" style="width: 100%;" data-url="{{ $tableStruct['url'] }}">
                		        <thead>
                		            <tr>
                		                @foreach ($tableStruct['datatable_1'] as $struct)
                		                	<th class="text-center v-middle"
                		                		data-columns-name="{{ $struct['name'] ?? '' }}"
                		                		data-columns-data="{{ $struct['data'] ?? '' }}"
                		                		data-columns-label="{{ $struct['label'] ?? '' }}"
                		                		data-columns-sortable="{{ $struct['sortable'] === true ? 'true' : 'false' }}"
                		                		data-columns-width="{{ $struct['width'] ?? '' }}"
                		                		data-columns-class-name="{{ $struct['className'] ?? '' }}"
                		                		style="{{ isset($struct['width']) ? 'width: '.$struct['width'].'; ' : '' }}">
                		                		{{ $struct['label'] }}
                		                	</th>
                		                @endforeach
                		            </tr>
                		        </thead>
                		        <tbody></tbody>
                		    </table>
                	    @endif
                	</div>
                </div>

            </div>
        </div>
        
    </div>
@endsection