routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', '/admin/home');

Route::prefix("admin")->group(function(){
    Auth::routes();
});

Route::middleware('auth')
    ->prefix("admin")
    ->group(
        function () {
            Route::namespace('Dashboard')
            ->group(
                function () {
                    Route::get('home', 'DashboardController@index')->name('home');
                    Route::post('progress', 'DashboardController@progress')->name('dashboard.progress');
                    Route::post('chartFinding', 'DashboardController@chartFinding')->name('dashboard.chartFinding');
                    Route::post('chartFollowup', 'DashboardController@chartFollowup')->name('dashboard.chartFollowup');
                    Route::post('chartStage', 'DashboardController@chartStage')->name('dashboard.chartStage');
                    Route::get('language/{lang}/setLang', 'DashboardController@setLang')->name('setLang');
                }
            );

            // Ajax
            Route::prefix('ajax')
                ->name('ajax.')
                ->group(
                    function () {
                        Route::post('saveTempFiles', 'AjaxController@saveTempFiles')->name('saveTempFiles');
                        Route::delete('file/{id}', 'AjaxController@deletTempFile')->name('deleteTempFile');
                        Route::get('testNotification/{emails}', 'AjaxController@testNotification')->name('testNotification');
                        Route::post('userNotification', 'AjaxController@userNotification')->name('userNotification');
                        Route::get('userNotification/{notification}/read', 'AjaxController@userNotificationRead')->name('userNotificationRead');
                        // Ajax Modules
                        Route::post('{search}/selectRole', 'AjaxController@selectRole')->name('selectRole');
                        Route::post('{search}/selectUser', 'AjaxController@selectUser')->name('selectUser');
                        Route::post('{search}/selectTrainingType', 'AjaxController@selectTrainingType')->name('selectTrainingType');
                        Route::post('{search}/selectTraining', 'AjaxController@selectTraining')->name('selectTraining');
                    }
                );

            // Setting
            Route::namespace('Setting')
            ->prefix('setting')
            ->name('setting.')
            ->group(
                function () {
                    Route::namespace('Role')
                        ->group(
                            function () {
                                Route::get('role/import', 'RoleController@import')->name('role.import');
                                Route::post('role/importSave', 'RoleController@importSave')->name('role.importSave');
                                Route::get('role/{record}/permit', 'RoleController@permit')->name('role.permit');
                                Route::patch('role/{record}/grant', 'RoleController@grant')->name('role.grant');
                                Route::grid('role', 'RoleController');
                            }
                        );
                    Route::namespace('Permission')
                    ->group(
                        function () {
                            Route::get('permission/import', 'PermissionController@import')->name('permission.import');
                            Route::post('permission/importSave', 'PermissionController@importSave')->name('permission.importSave');
                            Route::grid('permission', 'PermissionController');
                        }
                    );
                    // Route::namespace('Flow')
                    //     ->group(
                    //         function () {
                    //             Route::get('flow/import', 'FlowController@import')->name('flow.import');
                    //             Route::post('flow/importSave', 'FlowController@importSave')->name('flow.importSave');
                    //             Route::grid('flow', 'FlowController');
                    //         }
                    //     );
                    Route::namespace('User')
                        ->group(
                            function () {
                                Route::get('user/import', 'UserController@import')->name('user.import');
                                Route::post('user/importSave', 'UserController@importSave')->name('user.importSave');
                                Route::post('user/{record}/resetPassword', 'UserController@resetPassword')->name('user.resetPassword');
                                Route::grid('user', 'UserController');

                                Route::get('profile', 'ProfileController@index')->name('profile.index');
                                Route::post('profile', 'ProfileController@updateProfile')->name('profile.updateProfile');
                                Route::get('profile/notification', 'ProfileController@notification')->name('profile.notification');
                                Route::post('profile/gridNotification', 'ProfileController@gridNotification')->name('profile.gridNotification');
                                Route::get('profile/activity', 'ProfileController@activity')->name('profile.activity');
                                Route::post('profile/gridActivity', 'ProfileController@gridActivity')->name('profile.gridActivity');
                                Route::get('profile/changePassword', 'ProfileController@changePassword')->name('profile.changePassword');
                                Route::post('profile/changePassword', 'ProfileController@updatePassword')->name('profile.updatePassword');
                            }
                        );
                    Route::namespace('Activity')
                        ->group(
                            function () {
                                Route::get('activity/export', 'ActivityController@export')->name('activity.export');
                                Route::grid('activity', 'ActivityController');
                            }
                        );
                }
            );

            // Master
            Route::namespace("Master")->prefix("master")->name("master.")->group(function() {
                Route::grid("training-types", "TrainingTypeController");
                Route::grid("trainings", "TrainingController");
                Route::grid("certificates", "CertificateController");
            });

            Route::namespace("Transaction")->prefix("transaction")->name("transaction.")->group(function() {
                Route::grid("participants", "Participant\ParticipantController");
                Route::grid("certificates", "Participant\ParticipantCertificateController");
            });

            // Web Transaction Modules
            foreach (\File::allFiles(__DIR__ . '/webs') as $file) {
                require $file->getPathname();
            }
        }
    );

app/Models/Example/Crud/Crud.php
<?php

namespace App\Models\Example\Crud;

use App\Models\Auth\User;
use App\Models\Model;
use App\Models\Traits\HasApprovals;
use App\Models\Traits\HasFiles;
use Carbon\Carbon;

class Crud extends Model
{
    use HasFiles;
    use HasApprovals;

    protected $table = 'trans_cruds';

    protected $fillable = [
        'year',
        'date',
        'range_start',
        'range_end',
        'input',
        'option',
        'textarea',
        'status',
    ];

    /*******************************
     ** MUTATOR
     *******************************/
    public function setDateAttribute($value)
    {
        $this->attributes['date'] = Carbon::createFromFormat('d/m/Y', $value);
    }

    public function setRangeStartAttribute($value)
    {
        $this->attributes['range_start'] = Carbon::createFromFormat('d/m/Y', $value);
    }

    public function setRangeEndAttribute($value)
    {
        $this->attributes['range_end'] = Carbon::createFromFormat('d/m/Y', $value);
    }

    /*******************************
     ** ACCESSOR
     *******************************/
    public function getShowDateAttribute($value)
    {
        return Carbon::parse($this->date)->format('d/m/Y');
    }

    public function getShowRangeStartAttribute($value)
    {
        return Carbon::parse($this->range_start)->format('d/m/Y');
    }

    public function getShowRangeEndAttribute($value)
    {
        return Carbon::parse($this->range_end)->format('d/m/Y');
    }

    /*******************************
     ** RELATION
     *******************************/
    public function details()
    {
        return $this->hasMany(CrudDetail::class, 'crud_id');
    }

    public function cc()
    {
        return $this->belongsToMany(User::class, 'trans_cruds_cc', 'crud_id', 'user_id');
    }

    /*******************************
     ** SCOPE
     *******************************/
    public function scopeGrid($query)
    {
        return $query->latest();
    }

    public function scopeFilters($query)
    {
        return $query->filterBy(['year']);
    }

    /*******************************
     ** SAVING
     *******************************/
    public function handleStoreOrUpdate($request)
    {
        $this->beginTransaction();
        try {
            $this->fill($request->all());
            $this->status = 'draft';
            $this->save();
            $this->saveDetails($request);
            $this->saveFiles($request);
            $this->saveLogNotify();

            if ($request->is_submit) {
                return $this->commitSaved(['redirectToModal' => route($request->routes.'.submit', $this->id)]);
            }

            return $this->commitSaved();
        } catch (\Exception $e) {
            return $this->rollbackSaved($e);
        }
    }

    public function saveDetails($request)
    {
        $ids = [];
        foreach ($request->details as $val) {
            $detail = $this->details()->firstOrNew(['id' => $val['id'] ?? 0]);
            $detail->fill($val);
            $this->details()->save($detail);
            $ids[] = $detail->id;
        }
        $this->details()->whereNotIn('id', $ids)->delete();
    }

    public function saveFiles($request)
    {
        $this->saveFilesByTemp($request->attachments, $request->module, 'attachments');
    }

    public function handleDestroy()
    {
        $this->beginTransaction();
        try {
            $this->saveLogNotify();
            $this->delete();

            return $this->commitDeleted();
        } catch (\Exception $e) {
            return $this->rollbackDeleted($e);
        }
    }

    public function handleSubmitSave($request)
    {
        $this->beginTransaction();
        try {
            $this->update(['status' => 'waiting.approval']);
            $this->cc()->sync($request->cc ?? []);
            $this->generateApproval($request->module);
            $this->saveLogNotify();

            $redirect = route(request()->get('routes').'.index');
            return $this->commitSaved(compact('redirect'));
        } catch (\Exception $e) {
            return $this->rollbackSaved($e);
        }
    }

    public function handleReject($request)
    {
        $this->beginTransaction();
        try {
            $this->rejectApproval($request->module, $request->note);
            $this->update(['status' => 'rejected']);
            $this->saveLogNotify();

            $redirect = route(request()->get('routes').'.index');
            return $this->commitSaved(compact('redirect'));
        } catch (\Exception $e) {
            return $this->rollbackSaved($e);
        }
    }

    public function handleApprove($request)
    {
        $this->beginTransaction();
        try {
            $this->approveApproval($request->module);
            if ($this->firstNewApproval($request->module)) {
                $this->update(['status' => 'waiting.approval']);
            } else {
                $this->update(['status' => 'completed']);
            }
            $this->saveLogNotify();

            $redirect = route(request()->get('routes').'.index');
            return $this->commitSaved(compact('redirect'));
        } catch (\Exception $e) {
            return $this->rollbackSaved($e);
        }
    }

    public function saveLogNotify()
    {
        $data = \Base::getModules(request()->get('module')).' Tahun '.$this->year;
        $routes = request()->get('routes');
        switch (request()->route()->getName()) {
            case $routes.'.store':
                $this->addLog('Membuat Data '.$data);
                break;
            case $routes.'.update':
                $this->addLog('Mengubah Data '.$data);
                break;
            case $routes.'.destroy':
                $this->addLog('Menghapus Data '.$data);
                break;
            case $routes.'.submitSave':
                $this->addLog('Submit Data '.$data);
                $this->addNotify([
                    'message' => 'Waiting Approval '.$data,
                    'url' => route($routes.'.approval', $this->id),
                    'user_ids' => $this->getNewUserIdsApproval(request()->get('module')),
                ]);
                break;
            case $routes.'.approve':
                $this->addLog('Menyetujui Data '.$data);
                $this->addNotify([
                    'message' => 'Waiting Approval '.$data,
                    'url' => route($routes.'.approval', $this->id),
                    'user_ids' => $this->getNewUserIdsApproval(request()->get('module')),
                ]);
                break;
            case $routes.'.reject':
                $this->addLog('Menolak Data '.$data.' dengan alasan: '.request()->get('note'));
                break;
        }
    }

    /*******************************
     ** OTHER FUNCTIONS
     *******************************/
    public function checkAction($action, $perms)
    {
        $user = auth()->user();

        switch ($action) {
            case 'create':
                return $user->checkPerms($perms.'.create');
                break;

            case 'edit':
                $checkStatus = in_array($this->status, ['new','draft','rejected']);
                return $checkStatus && $user->checkPerms($perms.'.edit');
                break;

            case 'show':
            case 'history':
                return $user->checkPerms($perms.'.view');
                break;

            case 'delete':
                $checkStatus = in_array($this->status, ['new','draft']);
                return $checkStatus && $user->checkPerms($perms.'.delete');
                break;

            case 'approval':
                if ($this->checkApproval(request()->get('module'))) {
                    $checkStatus = in_array($this->status, ['waiting.approval']);
                    return $checkStatus && $user->checkPerms($perms.'.view');
                }
                break;

            case 'tracking':
                $checkStatus = in_array($this->status, ['waiting.approval']);
                return $checkStatus && $user->checkPerms($perms.'.view');
                break;

            case 'print':
                $checkStatus = in_array($this->status, ['waiting.approval','completed']);
                return $checkStatus && $user->checkPerms($perms.'.view');
                break;
        }

        return false;
    }

    public function getOption($option = 'all')
    {
        $data = [
            1 => 'Option A',
            2 => 'Option B',
            3 => 'Option C',
            4 => 'Option D',
            5 => 'Option E',
        ];

        if ($option == 'all') return $data;

        return $data[$option] ?? null;
    }
}

app/Models/Globals/Files.php
<?php

namespace App\Models\Globals;

use App\Models\Model;

class Files extends Model
{
	protected $table = 'sys_files';

	protected $fillable = [
		'target_id',
		'target_type',
        'module',
		'file_name',
        'file_path',
        'file_size',
        'flag', //Tambahkan flag jika ada kondisi tertentu
	];

    protected $appends = [
        'file_url',
    ];

    public function target()
    {
        return $this->morphTo();
    }

    public function getFileUrlAttribute()
    {
        if ($this->file_path) {
            // Handle jika ada yg menyimpan full url
            $file_path = explode('/storage/', $this->file_path);
            $file_path = end($file_path);
            return url('storage/'.$file_path);
        }
        return null;
    }

    public function getFileTypeAttribute()
    {
        if ($this->file_path) {
            $extension = explode('.', trim($this->file_path));
            return strtolower(end($extension));
        }
        return null;
    }

    public function getFileIconAttribute()
    {
        $icon = 'far fa-file-alt';
        $type = $this->file_type;
        if ($type == 'pdf') {
            $icon = 'text-danger far fa-file-pdf';
        }
        else if($type == 'xlsx') {
            $icon = 'text-success far fa-file-excel';
        }
        else if($type == 'jpg' || $type == 'png') {
            $icon = 'text-warning far fa-file-image';
        }
        else if($type == 'ppt') {
            $icon = 'text-danger far fa-file-powerpoint';
        }
        else if($type == 'docx') {
            $icon = 'text-primary far fa-file-word';
        }
        return $icon.' '.$type;
    }
}

resources/views/example/crud/edit.blade.php
@extends('layouts.form', ['container' => 'container-fluid'])

@section('action', route($routes.'.update', $record->id))

@section('card-body')
	@method('PATCH')
	@include($views.'.includes.notes')
	<br>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Tahun') }}</label>
				<div class="col-md-8 parent-group">
					<input type="text" name="year"
						class="form-control base-plugin--datepicker-3"
						value="{{ $record->year }}"
						data-options='@json([
							"startDate" => (string) $record->year,
							"endStart" => ""
						])'
						placeholder="{{ __('Tahun') }}">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Tanggal') }}</label>
				<div class="col-md-8 parent-group">
					<input type="text" name="date"
						class="form-control base-plugin--datepicker"
						value="{{ $record->show_date }}"
						data-options='@json([
							"startDate" => (string) $record->show_date,
							"endStart" => ""
						])'
						placeholder="{{ __('Tanggal') }}">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Rentang Tanggal') }}</label>
				<div class="col-md-8 parent-group">
					<div class="input-group">
						<input type="text" name="range_start"
							class="form-control base-plugin--datepicker range_start"
							value="{{ $record->show_range_start }}"
							data-options='@json([
								"orientation" => "bottom",
								"startDate" => (string) $record->show_range_start,
								"endStart" => ""
							])'
							placeholder="{{ __('Mulai') }}">
						<div class="input-group-append">
							<span class="input-group-text">
								<i class="la la-ellipsis-h"></i>
							</span>
						</div>
						<input type="text" name="range_end"
							class="form-control base-plugin--datepicker range_end"
							value="{{ $record->show_range_end }}"
							data-options='@json([
								"orientation" => "bottom",
								"startDate" => (string) $record->show_range_start,
								"endStart" => ""
							])'
							placeholder="{{ __('Selesai') }}">
					</div>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Lampiran') }}</label>
				<div class="col-md-8 parent-group">
					@php
						$files = $record->files($module)->where('flag', 'attachments')->get();
					@endphp
					<div class="custom-file">
					    <input type="hidden"
					    	name="attachments[uploaded]"
					    	class="uploaded"
					    	value="{{ $files->count() ? 1 : null }}">
					    <input type="file" multiple
					    	class="custom-file-input base-form--save-temp-files"
					    	data-name="attachments"
					    	data-container="parent-group"
					    	data-max-size="20024"
					    	data-max-file="100"
					    	@if($files->count() >= 100) disabled @endif
					    	accept="*">
					    <label class="custom-file-label">@if($files->count()) Add @else Choose @endif File</label>
					</div>
					@foreach ($files as $file)
					    <div class="progress-container w-100" data-uid="{{ $file->id }}">
					        <div class="alert alert-custom alert-light fade show py-2 px-4 mb-0 mt-2 success-uploaded" role="alert">
					            <div class="alert-icon">
					                <i class="{{ $file->file_icon }}"></i>
					            </div>
					            <div class="alert-text text-left">
					                <input type="hidden"
					                	name="attachments[files_ids][]"
					                	value="{{ $file->id }}">
					                <div>Uploaded File:</div>
					                <a href="{{ $file->file_url }}" target="_blank" class="text-primary">
					                	{{ $file->file_name }}
					                </a>
					            </div>
					            <div class="alert-close">
					                <button type="button"
					                	class="close base-form--remove-temp-files"
					                	data-toggle="tooltip"
					                	data-original-title="Remove">
					                    <span aria-hidden="true">
					                        <i class="ki ki-close"></i>
					                    </span>
					                </button>
					            </div>
					        </div>
					    </div>
					@endforeach
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Input') }}</label>
				<div class="col-md-8 parent-group">
					<input type="text" name="input"
						class="form-control"
						value="{{ $record->input }}"
						placeholder="{{ __('Input') }}">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Option') }}</label>
				<div class="col-md-8 parent-group">
					<select name="option"
						class="form-control base-plugin--select2"
						placeholder="{{ __('Pilih Salah Satu') }}">
						<option value="">{{ __('Pilih Salah Satu') }}</option>
						@foreach ($options as $key => $text)
							<option value="{{ $key }}" @if($key == $record->option) selected @endif>{{ $text }}</option>
						@endforeach
					</select>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Textarea') }}</label>
				<div class="col-md-8 parent-group">
					<textarea name="textarea"
						class="form-control"
						placeholder="{{ __('Textarea') }}">{!! $record->textarea !!}</textarea>
				</div>
			</div>

		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-bordered table-detail">
					<thead>
						<tr>
							<th class="text-center width-60px">No</th>
							<th class="text-center">Example</th>
							<th class="text-center">Jabatan</th>
							<th class="text-center">User</th>
							<th class="text-center">Deskripsi</th>
							<th class="text-center width-60px valign-middle">
								<button type="button"
									class="btn btn-sm btn-icon btn-circle btn-primary btn-add">
									<i class="fa fa-plus"></i>
								</button>
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($record->details as $detail)
							<tr data-key="{{ $loop->iteration }}">
								<td class="text-center no">{{ $loop->iteration }}</td>
								<td class="text-left parent-group" style="width: 250px; max-width: 250px;">
									{{-- Manual Select2 --}}
									<select name="details[{{ $loop->iteration }}][example_id]"
										class="form-control base-plugin--select2"
										placeholder="{{ __('Pilih Salah Satu') }}">
										<option value="">{{ __('Pilih Salah Satu') }}</option>
										@foreach ($examples as $val)
											<option value="{{ $val->id }}" @if($val->id == $detail->example_id) selected @endif>{{ $val->name }}</option>
										@endforeach
									</select>
								</td>
								<td class="text-left parent-group" style="width: 250px; max-width: 250px;">
									{{-- Ajax Select2 --}}
									<select name="details[{{ $loop->iteration }}][position_id]"
										class="form-control base-plugin--select2-ajax position_id"
										data-url="{{ route('ajax.selectPosition', ['search' => 'all']) }}"
										placeholder="{{ __('Pilih Salah Satu') }}">
										<option value="">{{ __('Pilih Salah Satu') }}</option>
										@if ($detail->user && ($position = $detail->user->position))
											<option value="{{ $position->id }}" selected>{{ $position->name }}</option>
										@endif
									</select>
								</td>
								<td class="text-left parent-group" style="width: 250px; max-width: 250px;">
									{{-- Ajax Select2 Combobox --}}
									<select name="details[{{ $loop->iteration }}][user_id]"
										class="form-control base-plugin--select2-ajax user_id"
										data-url="{{ route('ajax.selectUser', [
											'search' => 'by_position',
											'position_id' => '',
										]) }}"
										data-url-origin="{{ route('ajax.selectUser', [
											'search' => 'by_position'
										]) }}"
										@if (!$detail->user) disabled  @endif
										placeholder="{{ __('Pilih Salah Satu') }}">
										<option value="">{{ __('Pilih Salah Satu') }}</option>
										@if ($user = $detail->user)
											<option value="{{ $user->id }}" selected>{{ $user->name }} ({{ $user->position->name }})</option>
										@endif
									</select>
								</td>
								<td class="text-left parent-group">
									<textarea name="details[{{ $loop->iteration }}][description]"
										class="form-control"
										placeholder="{{ __('Textarea') }}">{!! $detail->description !!}</textarea>
								</td>
								<td class="text-center valign-middle">
									<button type="button"
										@if($loop->count == 1) disabled @endif
										class="btn btn-sm btn-icon btn-circle btn-danger btn-remove">
										<i class="fa fa-trash"></i>
									</button>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
@endsection

@section('card-footer')
	<div class="d-flex justify-content-between">
		@include('layouts.forms.btnBack')
		@include('layouts.forms.btnDropdownSubmit')
	</div>
@endsection

@push('scripts')
	@include($views.'.includes.scripts')
@endpush

resources/views/example/crud/show.blade.php
@extends('layouts.page', ['container' => 'container-fluid'])

@section('card-body')
	<div class="row">
		<div class="col-md-6">
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Tahun') }}</label>
				<div class="col-md-8 parent-group">
					<input type="text" class="form-control" value="{{ $record->year }}" disabled>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Tanggal') }}</label>
				<div class="col-md-8 parent-group">
					<input type="text" class="form-control" value="{{ $record->show_date }}" disabled>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Rentang Tanggal') }}</label>
				<div class="col-md-8 parent-group">
					<div class="input-group">
						<input type="text" class="form-control" value="{{ $record->show_range_start }}" disabled>
						<div class="input-group-append">
							<span class="input-group-text">
								<i class="la la-ellipsis-h"></i>
							</span>
						</div>
						<input type="text" class="form-control" value="{{ $record->show_range_end }}" disabled>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Lampiran') }}</label>
				<div class="col-md-8 parent-group">
					@php
						$files = $record->files($module)->where('flag', 'attachments')->get();
					@endphp
					@foreach ($files as $file)
					    <div class="progress-container w-100" data-uid="{{ $file->id }}">
					        <div class="alert alert-custom alert-light fade show py-2 px-4 mb-0 mt-2 success-uploaded" role="alert">
					            <div class="alert-icon">
					                <i class="{{ $file->file_icon }}"></i>
					            </div>
					            <div class="alert-text text-left">
					                <input type="hidden" 
					                	name="attachments[files_ids][]" 
					                	value="{{ $file->id }}">
					                <div>Uploaded File:</div>
					                <a href="{{ $file->file_url }}" target="_blank" class="text-primary">
					                	{{ $file->file_name }}
					                </a>
					            </div>
					            <div class="alert-close">
					                <button type="button" 
					                	class="close base-form--remove-temp-files" 
					                	data-toggle="tooltip" 
					                	data-original-title="Remove">
					                    <span aria-hidden="true">
					                        <i class="ki ki-close"></i>
					                    </span>
					                </button>
					            </div>
					        </div>
					    </div>
					@endforeach
					@if ($files->count() == 0)
						<div class="col-form-label">File tidak tersedia!</div>
					@endif
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Input') }}</label>
				<div class="col-md-8 parent-group">
					<input type="text" class="form-control" value="{{ $record->input }}" disabled>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Option') }}</label>
				<div class="col-md-8 parent-group">
					<input type="text" class="form-control" value="{{ $record->getOption($record->option) }}" disabled>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-4 col-form-label">{{ __('Textarea') }}</label>
				<div class="col-md-8 parent-group">
					<textarea class="form-control" disabled>{!! $record->textarea !!}</textarea>
				</div>
			</div>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-bordered table-detail">
					<thead>
						<tr>
							<th class="text-center width-60px">No</th>
							<th class="text-center">Example</th>
							<th class="text-center">Jabatan</th>
							<th class="text-center">User</th>
							<th class="text-center">Deskripsi</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($record->details as $detail)
							<tr data-key="{{ $loop->iteration }}">
								<td class="text-center no">{{ $loop->iteration }}</td>
								<td class="text-left parent-group" style="width: 250px; max-width: 250px;">
									{{ $detail->example->name ?? '' }}
								</td>
								<td class="text-left parent-group" style="width: 250px; max-width: 250px;">
									{{ $detail->user->position->name ?? '' }}
								</td>
								<td class="text-left parent-group" style="width: 250px; max-width: 250px;">
									{{ $detail->user->name ?? '' }}
								</td>
								<td class="text-left parent-group">
									<div style="white-space: pre-wrap;">{!! $detail->description !!}</div>
								</td>
							</tr>
						@endforeach
						@if ($record->details->count() == 0)
							<tr>
								<td class="text-center" colspan="5">Data tidak tersedia!</td>
							</tr>
						@endif
					</tbody>
				</table>
			</div>
		</div>
	</div>
@endsection

@section('buttons')
@endsection